import test from 'node:test';
import assert from 'node:assert/strict';
import { WaveManager, StageState } from '../src/combat/WaveManager.js';

class State { constructor() { this.data = { progression: {}, combat: { enemies: [], currentWave: 0, totalWaves: 0, state: 'idle' } }; } get(path) { return structuredClone(path.split('.').reduce((o, k) => o[k], this.data)); } set(path, value) { const keys = path.split('.'); const last = keys.pop(); let target = this.data; keys.forEach((k) => { target = target[k]; }); target[last] = structuredClone(value); } batch(label, changes) { changes.forEach((change) => this.set(change.path, change.value)); } }
const stages = { one: { id: 'one', zoneId: 'fittoa', displayStage: 1, totalWaves: 2, waves: [[{ id: 'slime', count: 1 }], [{ id: 'goblin', count: 2 }]] } };
const factory = { createEnemy: (id, extra) => ({ id: `${id}-${Math.random()}`, type: 'enemy', isAlive: true, ...extra }) };
test('stage begins then spawns its first wave', () => { const state = new State(); const manager = new WaveManager({ stateManager: state, eventBus: { emit() {} }, events: {}, entityFactory: factory, stages, waveDelay: 10 }); manager.startStage('one'); assert.equal(state.data.combat.state, StageState.ENTERING); manager.update(250); assert.equal(state.data.combat.currentWave, 1); assert.equal(state.data.combat.enemies.length, 1); });
test('clearing final wave transitions to stage clear', () => { const state = new State(); const emitted = []; const manager = new WaveManager({ stateManager: state, eventBus: { emit: (...args) => emitted.push(args) }, events: { WAVE_CLEARED: 'wave', STAGE_CLEARED: 'stage' }, entityFactory: factory, stages, waveDelay: 10 }); manager.startStage('one'); manager.update(250); state.data.combat.enemies = []; manager.update(1); manager.update(10); state.data.combat.enemies = []; manager.update(1); manager.update(10); assert.equal(state.data.combat.state, StageState.STAGE_CLEAR); assert.ok(emitted.some(([event]) => event === 'stage')); });
test('portal switches safely to stage select', () => { const state = new State(); const manager = new WaveManager({ stateManager: state, eventBus: { emit() {} }, events: {}, entityFactory: factory, stages }); manager.startStage('one'); manager.portalToStageSelect(); assert.equal(state.data.combat.state, StageState.STAGE_SELECT); assert.equal(state.data.combat.enemies.length, 0); });
